name: Build application

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "v*.*.*"

env:
  PROTOC_VERSION: 3.14.0
  GO_VERSION: 1.21.1

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Setup protobuf
        run: |
          PROTOC_ZIP=protoc-${{ env.PROTOC_VERSION }}-linux-x86_64.zip
          curl -OL https://github.com/google/protobuf/releases/download/v${{ env.PROTOC_VERSION }}/$PROTOC_ZIP
          sudo unzip -o $PROTOC_ZIP -d /usr/local/protoc
          sudo chmod +xr -R /usr/local/protoc
          sudo ln -s /usr/local/protoc/bin/protoc /usr/local/bin
          sudo ln -s /usr/local/protoc/include/google /usr/local/include/google
      - name: Lint programs
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          skip-pkg-cache: true
          skip-build-cache: true
          skip-go-installation: true
      - name: Install protoc-gen-go and protoc-gen-go-grpc
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - name: Add Go bin to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Build app
        run: |
          make all tag=ci
